### ISSUE TITLE
ValueError: Please specify agent_interface_format.

### ISSUE THREAD

**Issue by haine92** [llSourcell/A-Guide-to-DeepMinds-StarCraft-AI-Environment#14]
I try to run it. I did everything told in the README.md file and I also replaced the correct line with `from absl import flags`.

Now I got an other error message : 

> Traceback (most recent call last):
>   File "/home/kiki92/PycharmProjects/untitled1/A-Guide-to-DeepMinds-StarCraft-AI-Environment/train_mineral_shards.py", line 51, in <module>
>     main()
>   File "/home/kiki92/PycharmProjects/untitled1/A-Guide-to-DeepMinds-StarCraft-AI-Environment/train_mineral_shards.py", line 24, in main
>     visualize=True) as env:
>   File "/home/kiki92/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 248, in __init__
>     raise ValueError("Please specify agent_interface_format.")
> ValueError: Please specify agent_interface_format.

Any idea ?

**Comment by haine92** [comment]
I know that in the train_mineral_shards.py, there is at some point the instantiation of a sc2_env object. In the sc2_env.py, `agent_interface_format` is supposed to be one of the argument at the initialization but there is nothing (and thats what is causing the problem). Any idea what I'm suppose to put in ?

**Comment by RedPlatypus** [comment]
```python
with sc2_env.SC2Env(
      _only_use_kwargs=False,
      map_name="CollectMineralShards",
      step_mul=step_mul,
      visualize=True,
      agent_interface_format=sc2_env.AgentInterfaceFormat(
              feature_dimensions=sc2_env.Dimensions(
                  screen=64,
                  minimap=64)),
  ) as env:
```
Hopefully this helps, still can't find docs on this, just random examples around the web of what it should be. Let me know if you find doc's in the end on what `agent_interface_format` should be.

**Comment by fdgvdfgtrvgtrvg** [comment]
Hi  i fixed this ValueError but got another one: 
AssertionError: expected file or str, got <ptvsd.repl._ReplOutput object at 0x0000026CC5BF99B0>
Any idea ?
