### ISSUE TITLE
All arguments must be passed as keyword arguments

### ISSUE THREAD

**Issue by snurkabill** [llSourcell/A-Guide-to-DeepMinds-StarCraft-AI-Environment#2]
Hello, 
I've been trying to run your tutorial but I am getting this error: 

```
python3 train_mineral_shards.py 
Traceback (most recent call last):
  File "train_mineral_shards.py", line 51, in <module>
    main()
  File "train_mineral_shards.py", line 24, in main
    visualize=True) as env:
  File "/home/snurkabill/.local/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 116, in __init__
    raise ValueError("All arguments must be passed as keyword arguments.")
ValueError: All arguments must be passed as keyword arguments.
```

Could you please point me to correct direction?

**Comment by timzarhansen** [comment]
sadly i have the same problem after installing everything
any help out there?

**Comment by Log234** [comment]
In the file "train_mineral_shards.py" replace line 22:
`"CollectMineralShards",`
with:
`map_name="CollectMineralShards",`
